### ISSUE TITLE
How to ignore wekends when using count_gaps

### ISSUE THREAD

**Issue by APramov** [tidyverts/tsibble#81] opened 2019-01-30 10:32 UTC
Hi,
appologies if this is not the right place to ask questions about the package (if so, please  let me know where I can).  I just read the paper on tsibble (and found out about it) and I'd love to start using it for my analysis, it looks great!

About my problem: I work with financial time series data and would like to know if there is a way to let `count_gaps `ignore the missing weekends, as markets are closed on the wekend and there would never be any data there.  I tried googling an answer to this but wasn't successfull. 

Thank you

**Comment by earowang** [comment] 2019-01-30 11:00
Please see https://github.com/tidyverts/tsibble/issues/18 which hasn't been implemented yet.

**Comment by earowang** [comment] 2019-01-31 11:01
Currently, there's no way that `*_gaps()` can ignore weekends. A general problem is to allow for a user-defined calendar upon creating a tsibble. I'm not aware that any R package provides flexible tools to handle business calendars in terms of date, date-times and intraday. I'm closing this issue as the duplicate of https://github.com/tidyverts/tsibble/issues/18 .

**Closed by earowang** 2019-01-31 11:01 UTC
