### ISSUE TITLE
Cannot bind_rows() with tsibbles

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/tsibble#185] opened 2020-04-24 08:00 UTC
Possibly an upstream issue/change:
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tsibble)
bind_rows(
  slice(tourism, 1:100),
  slice(tourism, 101:n())
)
#> Error in vec_rbind(!!!dots, .names_to = .id): Internal error in `df_assign()`: Proxy of type `double` incompatible with type `character`.
```

<sup>Created on 2020-04-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by earowang** [comment] 2020-04-24 08:26
it's just a duplicate of https://github.com/tidyverts/tsibble/issues/183

**Comment by earowang** [comment] 2020-04-24 08:27
yes, it's related to vctrs https://github.com/r-lib/vctrs/issues/1021

**Closed as completed** 2020-04-30 02:32 UTC
